# Generated by Django 6.0.6 on 2026-07-01 18:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_location', models.CharField(max_length=255)),
                ('current_location_lat', models.FloatField(blank=True, null=True)),
                ('current_location_lng', models.FloatField(blank=True, null=True)),
                ('pickup_location', models.CharField(max_length=255)),
                ('pickup_location_lat', models.FloatField(blank=True, null=True)),
                ('pickup_location_lng', models.FloatField(blank=True, null=True)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('dropoff_location_lat', models.FloatField(blank=True, null=True)),
                ('dropoff_location_lng', models.FloatField(blank=True, null=True)),
                ('current_cycle_used_hrs', models.FloatField()),
                ('driver_name', models.CharField(default='Driver', max_length=100)),
                ('carrier_name', models.CharField(default='N/A', max_length=100)),
                ('truck_number', models.CharField(default='N/A', max_length=50)),
                ('total_distance_miles', models.FloatField(blank=True, null=True)),
                ('total_duration_hours', models.FloatField(blank=True, null=True)),
                ('route_geometry', models.JSONField(blank=True, null=True)),
                ('route_summary', models.JSONField(blank=True, null=True)),
                ('daily_logs', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
